### ISSUE TITLE
DG To-Do

### ISSUE THREAD

**Issue by yusufaine** [AY2122S2-CS2103T-T17-2/tp#254]
Just to keep track of the things we need to do, some of them have been done already so you can just mark them as done.

# Deliverable:
11 Apr -- UG, DG, PPP
13 Apr -- Demo (record on 12)

---

# Things to do for DG:

- [x] Update TOC
- [x] Acknowledgement - delete 4th point on 3rd party/external libs
- [x] Update architecture diagram
- [x] Update sequence diagram for delete
- [x] Update component diagram 
- [x] Update UI diagram 
- [x] Update BetterModelClassDiagram 
- [x] Update Logic diagram 
- [x] Update Delete Sequence (Aglio Olio)
- [x] Update Parser class diagram
- [x] Update content of parsing (How parsing works)
- [x] #267
- [x] Update AlternateModelClassDiagram (inside the blue box)
- [x] Update Storage class diagram
- [x] Update content for Storage
- [x] Common classes -> seedu.address.commons (just before Implementation)
- [x] Implementation `clear`, include clear diagrams
- [x] Update undo/redo to McKitchen
- [x] Add Find enhancement
- [ ] MSS for features:
    - [x] Add, 
    - [x] Clear, 
    - [x] Delete, 
    - [ ] Edit, 
    - [ ] Exit, 
    - [x] Find, 
    - [ ] Help, 
    - [ ] List, 
    - [x] Reset, 
    - [x] View
- [x] Glossary
- [x] Update manual testing.
